-- load onedark first otherwise bufferline colors wont work
require("bare.onedark")
require("bare.buffer")
require("bare.status")
require("bare.netrw")
require("bare.lsp")
require("bare.cmp")
require("bare.fzf").setup()
require("bare.surround").setup()
require("bare.marks").setup()
require("bare.filetree").setup()
require("bare.pairs").setup()
require("bare.liveserver").setup()
