require('vim._core.ui2').enable({})
require("bare.theme").setup()
require("bare.options")
require("bare.keymaps")
require("bare.notify").setup()

vim.schedule(function()
  require("bare.buffer")
  require("bare.status")
  require("bare.git").setup()
  require("bare.pairs").setup()
  require("bare.preview").setup()
  require("bare.cmp")
  require("bare.netrw")

  require("bare.fzf").setup()
  require("bare.marks").setup()
  require("bare.surround").setup()
  require("bare.diagnostics").setup()
  require("bare.lsp")
  require("bare.picker")
  require("bare.floaterm")
  require("bare.hints").setup()
  require("bare.img").setup()
  require("bare.present").setup()
end)

vim.keymap.set("n", "<leader>e", function() require("bare.files").toggle() end, { desc = "Toggle file explorer" })
